ALTER TABLE rides ADD COLUMN type ENUM('open', 'closed') DEFAULT 'closed';
ALTER TABLE rides ADD COLUMN start_time TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE rides ADD COLUMN end_time TIMESTAMP NULL DEFAULT NULL;
